import xarray as xr
from pathlib import Path
import pandas as pd

data_path = "" # Add the full path of your directory that contains all the netcdf files

output_zarr_path = "" # Add the full path and filename of the zarr file generated by this script

files = sorted([f for f in Path(data_path).iterdir() if f.is_file() and f.suffix == '.nc'])

datasets = []
for file in files:
    ds = xr.open_dataset(file, chunks={})
    init_time = pd.Timestamp(ds.time.values[0]).floor('D') # init_time is the date of each file, I use the first value of the time dim
    ds = ds.rename({"time": "valid_time"}) # valid_time is the forecasts dates
    ds = ds.assign_coords(valid_time=ds.valid_time.dt.floor('D'))
    ds = ds.assign_coords(init_time=init_time)
    ds = ds.expand_dims('init_time')
    ds = ds.transpose('init_time', 'valid_time', 'lat', 'lon')
    datasets.append(ds)

combined = xr.concat(
    datasets,
    dim='init_time'
)

combined.chunk({"init_time": 1, "valid_time": 1}).to_zarr(Path(output_zarr_path), mode='w')